AllCops:
  TargetRubyVersion: 2.1
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/**/*'
    - 'Gemfile'
    - 'Guardfile'
    - 'Gemfile.lock'
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 15
Metrict/AbcSize:
  Enabled: false
Rails/TimeZone:
  Enabled: false
SignalException:
  Enabled: false
Style/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: false
Style/DotPosition:
  EnforcedStyle: leading
Style/BracesAroundHashParameters:
  Enabled: false
Style/Lambda:
  Enabled: false
