source 'https://rubygems.org'
ruby "2.1.5"

gem 'rails', '4.1.14'

gem 'acts_as_list'
gem 'animate-scss'
gem "autoprefixer-rails"
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-passenger'
gem 'capistrano-rails'
gem 'capistrano-npm'
gem 'carrierwave'
gem 'coffee-rails'
gem 'coffee-script-source', '1.8.0'
gem 'decent_decoration'
gem 'decent_exposure'
gem 'devise'
gem 'dotenv-rails'
gem 'draper'
gem 'flip'
gem 'fog'
gem 'font-awesome-rails'
gem 'gon'
gem 'google-analytics-rails'
gem 'google-api-client', require: 'google/api_client'
gem 'haml-rails'
gem 'haml_coffee_assets', github: 'netzpirat/haml_coffee_assets'
gem 'hipchat'
gem 'jquery-cookie-rails'
gem 'jquery-rails'
gem 'jquery-tablesorter'
gem 'jquery-ui-rails'
gem 'js_stack', '0.5.2'
gem 'konf'
gem 'messengerjs-rails'
gem 'mini_magick'
gem 'netguru_theme'
gem 'newrelic_rpm'
gem 'oj'
gem 'omniauth'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'pg'
gem 'rabl', '~> 0.11.5'
gem 'rack-mini-profiler', require: false
gem 'render_anywhere', require: false
gem 'rollbar'
gem 'ruby-trello'
gem 'rvm1-capistrano3', require: false
gem 'sass-rails'
gem 'searchlight'
gem 'selectize-rails'
gem 'simple_form'
gem 'slack-notifier'
gem 'sucker_punch'
gem 'therubyracer'
gem 'uglifier'
gem 'versionist'
gem 'whenever', require: false
gem 'httparty'
gem 'active_model_serializers'
gem 'react_webpack_rails', '0.0.4'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'xray-rails'
  gem 'gemsurance'
end

group :development, :test do
  gem 'awesome_print'
  gem 'capistrano-rvm', require: false
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'factory_girl_rails'
  gem 'faker'
end

group :test do
  gem 'capybara', '~> 2.4.4'
  gem 'codeclimate-test-reporter', require: false
  gem 'database_cleaner'
  gem 'phantomjs', require: 'phantomjs/poltergeist'
  gem 'poltergeist'
  gem 'rack_session_access'
  gem 'rspec-instafail'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'shoulda'
  gem 'spork-rails'
  gem 'timecop'
  gem 'webmock'
end
